version: '3.8'
services:
  exzork_mrpc:
    container_name: exzork_mrpc
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/mrpc
      - /mrpc/node_modules
      - /mrpc/build
    environment:
      - VIRTUAL_HOST=mrpc.exzork.me
      - LETSENCRYPT_HOST=mrpc.exzork.me
      - LETSENCRYPT_EMAIL=muhammadeko.if@gmail.com
networks:
  default :
    name: nginx-proxy